{
 "title": "Ingresos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clase",
    "query": "SELECT clase FROM dttn.trainsetclases;"
   },
   { "name": "ingreso", "query": "mensual, anual, conclusion" }
  ]
 },
 "panels": [
  {
   "title": "Conteo de Sancionados",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM dttn.trainsetclases WHERE clase = $clase;\n"
    }
   ]
  },
  {
   "title": "Distribución de Ingreso Mensual Por tipo de Falta",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n$ingreso as value\nFROM dttn.trainsetclases\nwhere clase = $clase;\n"
    },
    {
     "rawSql": "SELECT\n$ingreso as value\nFROM dttn.trainsetclases\nwhere clase = $clase;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos por Actividad Financiera",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, financieramed as fm, netomed as nm, netdev as nd\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos por Actividad Comercial",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, comercialmed as cm, netomed as nm, netdev as nd\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos por Servicios Profesionales",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, profesionalesmed as pm, netomed as nm, netdev as nd\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos por Ingreso Mensual",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, mensualmed as mm, netomed as nm, netdev as nd\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos por Ingreso Anual",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, anualmed as am, netomed as nm, netdev as nd\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  },
  {
   "title": "Dispersión de ingresos Totales Netos",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, netdev as nd, netomed as nm\nFROM dttn.train_stdev\nWHERE clase = $clase\nORDER by id;\n"
    }
   ]
  }
 ]
}